### ISSUE TITLE
Build problem on alpine

### ISSUE THREAD

**Issue by saucisson** [lip6/libITS#1]
When building `libITS` on `alpine`, there are is the following error:

```sh
/usr/include/fortify/stdio.h:68:28: error: inlining failed in call to always_inline 'vsnprintf': function body not available
 _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
```

And also what seems to be important warnings:

```sh
../its/etf/stream.c:87:6: note: code may be misoptimized unless -fno-strict-aliasing is used
```

You can use the following `Dockerfile`  to reproduce the problem:
```dockerfile
FROM alpine

RUN true \
 && apk add --no-cache --virtual .build-deps \
        autoconf \
        automake \
        binutils \
        bison \
        build-base \
        boost-dev \
        cmake \
        curl \
        flex \
        git \
        libtool \
        gmp-dev \
        libexecinfo-dev \
        expat-dev \
 && apk add --no-cache \
        bash \
        expat \
        gmp \
        libgmpxx \
        libexecinfo \
        openjdk8-jre-base \
&& true
RUN true \
 && git clone --depth=1 https://github.com/lip6/libDDD \
    && cd libDDD \
    && autoreconf -fi \
    && ./configure \
    && make install \
    && cd .. \
    && rm -rf libDDD* \
&& true
RUN true \
 && curl http://www.antlr3.org/download/antlr-3.4.tar.gz \
         --output antlr-3.4.tar.gz \
    && tar -xf antlr-3.4.tar.gz \
    && cp antlr-3.4/lib/antlr-3.4-complete.jar \
          /usr/local/lib/ \
    && cd ./antlr-3.4/runtime/C \
    && autoreconf -fi \
    && ./configure --enable-64bit \
    && make install \
    && cd ../../.. \
    && rm -rf antlr-3.4* \
&& true
RUN true \
 && git clone --depth=1 https://github.com/lip6/libITS \
    && cd libITS \
    && autoreconf -fi \
    && ./configure --with-antlrjar=/usr/local/lib/antlr-3.4-complete.jar \
    && make \
    && make install \
    && cd .. \
    && rm -rf libITS* \
&& true
RUN true \
 && apk del .build-deps \
 && true
```

**Comment by yanntm** [comment]
ETF and DVE code are both legacy C code taken from LTSmin and Divine respectively.
There are indeed a few warnings generated there, but it should not be critical.

vsnprintf is C99 standard, the issue is using Musl instead of Glibc in the Alpine container.

You could just take the static linked exe rather than building it; it should run without any dependencies (including glibc).

**Comment by yanntm** [comment]
I did a pass to reduce some warnings, 

Nothing critical, just small int->size_t changes.

Most warnings come from Antlr... or are about "unused code/return values"

We'd happily take a PR that helps build on Alpine, but this is low priority for us, we are fine with glibc and g++.

We don't even use clang currently on MacOS; our tool chain is GNU gcc on all platforms (win, mac, linux). This is what is tested and works.

Other systems may or may not work but we don't offer support for them.
