### ISSUE TITLE
Variables SDD

### ISSUE THREAD

**Issue by Neptunia94** [lip6/libITS#3]
1) Comment tester si une variable de nom [varName] existe dans le modèle ? (pour éviter le exit du getPredicate quand l'utilisateur a fait une faute d'orthographe)
2) Comment définir une équivalence de SDD basée sur un sous ensemble des variables ?
Soit V \subseteq Var , on veut définir SDD1 =V SDD2 si ProjV(SDD1) = ProjV(SDD2)

**Comment by yanntm** [comment]
1. model.getInstance()->getType()->getVarOrder()->getIndex(varname) ne doit pas rendre -1.
On est censés générer les requêtes, pas de raison qu'un programme fasse des typos, d'où le comportement un peu violent actuel. Il nous faudrait des exceptions pour faire propre.

2. Tu veux la transition https://github.com/lip6/libITS/blob/master/its/Type.hh#L107 observe je crois.
Donc tu lui passes un ss-ens des variables, et tu veux obs(SDD1) == obs(SDD2).
L'état des autres variables va à leur potentiel, lu dans le deuxième argument. Selon ce que tu fais c'est soit un chemin simple, soit "reachable". Passer reachable permet de refaire des intersections avec des états non abstraits/projetés.

**Comment by yanntm** [comment]
ces operations observe sont donc homogenes, on garde la longueur des chemins du DD. On pourrait faire une version qui projette vraiment, mais celle ci en pratique est souvent plus utile.

**Comment by Neptunia94** [comment]
Merci, je vais regarder ça
Florence

**Comment by yanntm** [comment]
ok je vais close l'issue, reopen si ça ne va pas pour ton besoin.
Donc sur observe, on a deux opérations duales, une pour obtenir la classe d'équivalence (observe) d'un ens d'états, et une pour revenir d'une classe d'équivalence à tous les états représentés (intersection).
