### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lip6/libITS#39]
I would like to point out that identifiers like “[`__PHILO_HH`](https://github.com/lip6/libITS/blob/10a8cb6031525874b52f5f7889e29851be797dd4/bin/philo.hh#L1 "Update candidate")” and “[`__TRAIN_HH__`](https://github.com/lip6/libITS/blob/f08749b6c6083dbd5e6caf8b8a1b731369bfe2e0/LTL/src/train.hh#L1 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by yanntm** [comment]
see https://github.com/lip6/libDDD/issues/38

**Comment by elfring** [comment]
:thinking: It seems that we stumble on another temporary disagreement about implementation details.

:thought_balloon: I would appreciate if [undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?") can be avoided for more software components.
