### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [lip6/libITS#40]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ITSModel](https://github.com/lip6/libITS/blob/10a8cb6031525874b52f5f7889e29851be797dd4/its/ITSModel.cpp#L45 "Destructor for ITSModel")
- [TypeBasics](https://github.com/lip6/libITS/blob/10a8cb6031525874b52f5f7889e29851be797dd4/its/TypeBasics.cpp#L14 "Destructor for TypeBasics")
- [Vertex](https://github.com/lip6/libITS/blob/10a8cb6031525874b52f5f7889e29851be797dd4/its/expression/expression.cpp#L207 "Destructor for Vertex")

**Comment by yanntm** [comment]
See see https://github.com/lip6/libDDD/issues/38

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
